version: "3.3"
services:
  blog_server:
    build:
      context: ../Server
      dockerfile: Dockerfile_app
    image: "blog/server:latest"
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - ../Server/app:/blog/Server/app
      - ../Server/deploy/gunicorn_config.py:/blog/Server/deploy/gunicorn_config.py
      - ../Server/DB:/blog/Server/DB
      - ../Server/StaticFile:/blog/Server/StaticFile
      - ../Server/log:/blog/Server/log
    depends_on:
      - blog_mysql
    networks:
      - mysql_net
      - server_net

  blog_mysql:
    build:
      context: ../mysql
      dockerfile: Dockerfile_mysql
    image: "blog/mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog_mysql_password"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/my.cnf:/etc/my.cnf
      - ../mysql/init:/docker-entrypoint-initdb.d
      - ../mysql/backup:/backup
    ports:
      - "3306:3306"
    networks:
      - mysql_net

  blog_nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile_nginx
    image: "blog/nginx:latest"
    restart: always
    ports:
      - "8088:8088"
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/logs:/usr/local/nginx/logs
      - ../Client/blog-web/build:/blog/Client/blog-web/build
      - ../nginx/nginx_default.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/cert:/etc/nginx/cert
    networks:
      - server_net
      
networks:
  mysql_net:
    driver: bridge
  server_net:
    driver: bridge
