version: "3.3"
services:
  blog_app:
    build:
      context: ../Server
      dockerfile: Dockerfile_app
    image: "blog/app:latest"
    ports:
      - "4444:4444"
    volumes:
      - ../Server/app:/blog/Server/app
      - ../Server/DB:/blog/Server/DB
      - ../Server/StaticFile:/blog/Server/StaticFile
      - ../Server/log:/blog/Server/log

  blog_nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile_nginx
    image: "blog/nginx:latest"
    ports:
      - "8088:8088"
      - "80:80"
    volumes:
      - ../nginx/logs:/usr/local/nginx/logs
      - ../Client/blog-web/build:/blog/Client/blog-web/build
      - ../nginx/nginx_default.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      
  blog_mysql:
    image: "mysql"
    restart: always
    container_name: blog_mysql
    valumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/my.cnf:/etc/my.cnf
      - ../mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "3306:3306"
