FROM python
MAINTAINER ThomasZhu 47029316@qq.com

RUN mkdir -p /blog/Server/app &&\
    mkdir -p /blog/Server/log &&\
    mkdir -p /blog/Server/deploy

COPY deploy/start_gunicorn.sh /blog/Server/deploy/start_gunicorn.sh
COPY app/requirements /blog/Server/requirements

WORKDIR /blog/Server

RUN pip3 install -r requirements &&\
    chmod +x ./deploy/start_gunicorn.sh

ENTRYPOINT ["./deploy/start_gunicorn.sh"]

EXPOSE 4444
