version: "3.3"
services:
  python_web:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: "app/app"
    ports:
      - "4444:4444"
    volumes:
      - ./app:/blog/Server/app
      - ./DB:/blog/Server/DB
      - ./StaticFile:/blog/Server/StaticFile
